spring:
  datasource:
    # 配置数据源信息（默认）
    type: com.zaxxer.hikari.HikariDataSource
    # 配置驱动
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://nicklorry.top:3306/easyroll?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: nick
    password: 15359503385nick
    hikari:
      max-lifetime: 120000
  redis:
    database: 1
    host: nicklorry.top
    port: 6379
    password: 15959558277Morbid

    jedis:
      pool:
        max-active: 20 # 连接池最大连接限制
        max-wait: -1 # 连接池最大阻塞等待时间（使用负数表示没有限制）
        max-idle: 10 # 连接池最大空闲连接
        min-idle: 0 # 连接池最小空闲连接
    timeout: 1000 # 连接超时时间（毫秒）

mybatis-plus:
  # 配置mybatis-plus日志（可以显示出动态生成的sql语句）
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 全局主键递增策略
      id-type: none
  # 扫描java bean的包，这样，在xml文件就可以直接使用类的名称作为类的别名了！
  type-aliases-package: com.system.roll.entity.pojo
  # 枚举类所在包扫描（该配置+枚举类中的注解，可以实现枚举类的自动映射）
  type-enums-package: com.system.roll.entity.constant.impl
  # 自定义类型处理器包扫描
  type-handlers-package: com.system.roll.handler.typehandler

